name: Dispatch Review

on:
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to solutions repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SOLUTIONS_DISPATCH_TOKEN }}
          repository: devdad-ru/booking-service-java-solutions
          event-type: student-pr-review
          client-payload: |
            {
              "pr_number": "${{ github.event.pull_request.number }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "branch": "${{ github.event.pull_request.head.ref }}",
              "repo": "${{ github.event.pull_request.head.repo.full_name }}"
            }